-- Generated by scripts/build-ml-local-recommendation-seed.py; do not edit by hand.
-- Source ML commit: 6b5b417411e04f5388d0eab39e1a57dee9d92676
-- Local/Docker demonstration data only. Availability and safety metadata are not verified.

INSERT INTO public.cuisine (id, code, name, created_at, updated_at, version)
VALUES
    ('a6c18258-c60d-5cf3-a901-0b234420e690', 'CHINESE', 'Chinese', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('5482ade5-b427-5148-bc53-d1878d6d3ac7', 'JAPANESE', 'Japanese', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('76c18e10-2041-5de1-8aaf-23b5c9de6388', 'SINGAPOREAN', 'Singaporean', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('bcfed92c-9aa9-584d-96c3-74cd906d4b91', 'WESTERN', 'Western', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0)
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.place (id, name, place_type, area, address_text, latitude, longitude, price_band, curation_status, created_at, updated_at, version)
VALUES
    ('fb61151e-a29a-507b-91b5-09907116fc35', 'The Royals Bistro', 'RESTAURANT', 'NUS University Town', '1 Create Way Singapore 138602', 1.30399654877953, 103.774032940413, NULL, 'ACTIVE', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'Udon Don Bar', 'RESTAURANT', 'NUS University Town', '1 Create Way Singapore 138602', 1.30399654877953, 103.774032940413, NULL, 'ACTIVE', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('a032d001-48a7-517a-bef0-95bc39640bca', 'Sloppy B', 'RESTAURANT', 'NUS Kent Ridge', 'University Sports Centre NUS', 1.300793, 103.775817, NULL, 'ACTIVE', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('5801e48d-a6bb-5ab5-b3e7-93791ea05ada', 'Ordinary Burgers', 'RESTAURANT', 'One@KentRidge', '1 Lower Kent Ridge Road Singapore 119082', 1.29494705784662, 103.784879314406, NULL, 'ACTIVE', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('5ad2685a-0bad-528f-a067-54c3916fd7ac', 'Syed Cafe', 'RESTAURANT', 'One@KentRidge', '1 Lower Kent Ridge Road Singapore 119082', 1.29494705784662, 103.784879314406, NULL, 'ACTIVE', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('92ec5b73-2358-548d-bbff-c8d5e4c49993', 'Mei Heong Yuen Dessert', 'RESTAURANT', '321 Clementi', '321 Clementi Avenue 3 Singapore 129905', 1.31158680791682, 103.76490400713, NULL, 'ACTIVE', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '04765498-0254-5ff3-b9ba-83bd7fdb2364', 'O''Drumlets Combo', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '0a5cc1b3-1e2d-5bf5-81fa-a5eae2d059fc', 'Teriyaki Chicken Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '0bb1066f-cfad-596b-a7dd-fbe560ae7d9c', 'Truffle Mushroom Cream (V)', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '0bce68cd-446e-59e8-b3e2-d68bb03becd3', 'Salted Egg Chicken Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '0e539386-bc6a-52d6-9617-8f59312e8b45', 'Lamb Shank Quesadilla', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '0fe496a3-3f52-5020-826b-9253a1da0fc1', 'Chicken Katsu Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '11c4ea94-f2b2-5822-a31b-5f72a1908a7e', 'Spicy Chicken Burger Meal', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '173ad3a6-6615-53f0-8539-5112e76a6676', 'Spicy Wafu Cheese Beef Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '18ac8d83-0a62-562f-8346-a0efd8932bf7', 'Portobello Mushroom Burger', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '1c6f2bff-afdd-5064-8219-45ffb5373f54', 'Miso Soup', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '1c76872c-a5d3-57a7-8991-c996a394fb1a', 'Chicken Tikka Briyani', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'SINGAPOREAN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '1faf4c76-8234-516b-9b73-56ffda4cce04', 'Sauteed Mushroom Burger with Miso Cream Sauce - Beef', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '2145097d-ec7f-5f51-a1c3-367b29502866', 'Marinara', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '23f49241-abac-554c-820c-bc7d0fb31950', 'Chicken Oyako Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '24f851c7-1db1-5e1d-8cb0-5a882e7dfb83', 'Mala Beef Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '28f63f1b-39b7-5169-b86f-6f96774f1e30', 'Beef Brisket & Cheese Sandwich', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '2a2e7742-46e4-57ae-83ff-b907afc9c08c', 'Dragon Chicken', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'SINGAPOREAN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '2d312ebd-8a94-5b38-adfc-bba80d95ee7e', 'Linguine with Chicken in Cream Sauce', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '2d436f77-c7b1-5001-add8-a65cdef4cd84', 'Classic Impossible™ Cheeseburger', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '2f9d9589-91b7-5274-aafb-9e08352050a7', 'Sauteed Mushroom Burger with Miso Cream Sauce - Chicken', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '33151fe8-08b4-55b7-a4f9-cbde5fb88ea2', 'Southern Buttermilk Chicken Burger', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '380070b0-2d83-56c0-b890-d82ec95ca7b4', 'Chicken Karaage Curry Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '3c72cc0d-a127-5d26-a922-5e435a0e8f3a', 'Black Glutinous Rice', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'CHINESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '41697031-4de4-580f-9093-6a0611c6de77', 'Grilled Chicken & Cheese Burger', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '475dc7c1-b1de-5c56-ab57-c11cc09cdb71', 'Shio Kosho Kuro Tonkotsu Ramen.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '487ac2e6-e14a-541e-8f18-ea0b4dd0e4f8', 'Spicy Tartar Chicken Nanban Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '4cc5b331-2615-50df-b40f-bc4290072258', 'Braised Lamb Shank', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '50325e55-299c-546f-a2fd-60d1edd6b054', 'Chicken Sausage & Spinach Penne in Tomato Cream Sauce', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '568ac2bc-d599-5976-94ca-1d4cb416cc68', 'Mala Beef Burger', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '5ef67236-67b2-5306-bac3-136b8df4a91f', 'Fish & Chips', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '5efe9b48-0227-5b51-93aa-cb0536bddd0d', 'Black Pepper Beef Yaki Udon.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '60504b15-43b0-5a05-b720-3097efce27e1', 'Salmon Spinach Linguine', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '6127f909-a450-52a4-8aeb-f79d724dc737', 'Chicken Katsu Curry Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '61518333-bb41-555a-8813-ae3ab23248c9', 'Chicken Shepherd''s Pie', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '670700d9-058d-5442-bf28-2509830d62cd', 'Prawn & Mushroom Linguine', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '672c1cf0-1e1c-5385-b7d7-c7bca85bf830', 'Cheese Combo', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'SINGAPOREAN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '67581f0e-6616-565b-ab6c-7d37fa50aaba', 'Grilled Chicken Chop', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '6a495fd3-0a08-53dd-8a48-233a67040aed', 'Beef Udon.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '6abd5ecb-ce6d-5715-b203-f013a4859e25', 'Spicy Chicken Burger', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '6af6f53d-9b2d-5e25-9412-62a63c066240', 'The Ordinary™ Classic Double Stack', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '6bc7a179-0bd0-5785-9411-05e5bf14f089', 'Classic Fish Fillet Burger', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '6bf7efba-bdfd-5d45-a8d2-6fe33f71358b', 'Truffle Mushroom Cream + Soup Set (V)', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '706301b9-c241-5a25-8996-1e241505d52f', 'Shio Kosho Tori Tonkotsu Ramen.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '7859347a-8be6-56b2-9587-843b0713653a', 'Smoked Salmon Sandwich', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '79e50103-e956-50f3-8d14-538de6346e87', 'Classic Impossible™ Cheeseburger Meal', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '7bc9a630-8a04-5e23-be39-89925ed1acfd', 'Classic Fish Fillet Burger Meal', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '8617fb7f-9194-5e14-8035-814189da1e5c', 'Garlic Combo', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'SINGAPOREAN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '86a822ef-d6b1-5efd-9bd9-7f97e5e8d544', 'Beef Rendang Nasi Lemak', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '895b781f-2c10-5686-be10-7a70ba77b58d', 'Linguine with Meatballs in Tomato Sauce', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '8a154e72-0da1-5f2e-b70c-5f7a76a31969', 'Nasi Lemak Sambal Prawns & Fish', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '8a202134-1667-59ce-9b3d-6d6d6b0c99de', 'Basic Chicken Linguine', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '96dd576f-2bed-5c87-b557-2e3324121b6a', 'Sukiyaki Beef Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '98d39635-da9f-5b6f-8ac5-238f4f589e6f', 'Krimchi + Soup Set', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '99d2a88b-6a6e-5e65-a10b-90f2dd4eb9c5', 'Chicken Tikka', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'SINGAPOREAN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT '9e937aee-8d13-5601-9410-a40134f81263', 'Pesto Verde', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'a02c9054-9543-55d1-a973-b35ccd95f63a', 'Mushroom & Spinach Penne in Tomato Cream', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'a117b7b1-9ae8-5b05-8632-6a40e2fbcecc', 'Beef Brisket Linguine', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'a1b9a1c5-95f3-521c-9cc0-314995f4f035', 'Spicy Garlic Beef Udon.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'a289307f-09cb-5410-a5c5-91f1d786716d', 'Mentaiyaki Beef & Ebiko Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'a328b1cf-cfae-5e79-bffe-4c53572a7153', 'Pan Seared Barramundi', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'a54eb9e2-9d8f-581f-ab17-2ca55861befa', 'Roasted Beef Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'a7b7a964-0431-5088-94bf-97468e11933d', 'Beef Curry Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'a9e9916c-0544-59df-8870-4cc8e690b0aa', 'Spicy Garlic Miso Chicken Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'ac3a9dc7-cf08-556f-b499-37db0a67edf8', 'Grilled Vege & Cheese Sandwich', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'b285c3af-2558-52a1-998e-3d3f8978535a', 'Salmon Burger with Garlic Aioli', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'b2dd50b0-0c43-588c-9f9e-f764607a50d1', 'Sauteed Vegetables & Mushroom Linguine', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'b2ec7ea8-127b-5436-8e9a-501e3daecf5d', 'Sauteed Wild Mushroom Linguine', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'b70f4586-fb3c-5cb1-b5c3-38061037054a', 'Marinara + Soup Set', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'bb110370-d9f2-5b6c-9d19-c330761b0745', 'Caesar Salad Grilled Chicken Thigh', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'bdef6c69-84c5-53e0-b82e-cf3e069c401e', 'Almond Black Glutinous Rice', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'CHINESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'c0fa4fdd-271d-5ec2-93d9-3ac99c9bc949', 'Chipopo', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'c11dc96a-d8a2-59eb-8cee-5cd7808903c3', 'Chapati Keema Set', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'SINGAPOREAN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'c214d041-869e-57ff-915d-4ea236b70e38', 'Pan-Fried Salmon', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'c7255486-dc39-51df-8693-79d6e7756a33', 'Chicken Combo', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'SINGAPOREAN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'c8c0240d-4b27-5052-9aa3-ab141d672e9b', 'Shio Kosho Aka Tonkotsu Ramen.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'c9331b63-bc1c-51b6-a961-71be5c3afc29', 'Krimchi', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'c96bb0b5-4abb-57e1-b2e6-84cd63a18b1e', 'Minced Katsu Curry Rice.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'cadad930-b162-506d-97d9-4b5b351c7e10', 'The Ordinary™ Classic Double Stack Meal', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'cb3ef44c-7cb9-56fc-8b83-b98638cfd7e2', 'Glutinous Rice Ball', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'CHINESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'd55958c2-0520-5c89-953a-9cd44d8f7e29', 'Ebimayo Katsu Burger Meal', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'd8cc1e85-41db-5c0f-92c2-61e6a2a68716', 'The Ordinary™ Classic Beef Burger', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'dbb22548-42a5-57b0-b8a4-851e3d6b8a2d', 'Beef Shepherd''s Pie', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'deb8016b-4218-5eef-af1f-e12e80c7b7c0', 'Tsukune & Chicken Karaage Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'e11a74c8-26d7-5810-bd21-eab724f64b7c', 'Black Pepper Beef Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'e2059627-d671-5381-a252-7521c3b374c3', 'Glutinous Rice', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'CHINESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'eaa8a66d-b7ec-5df3-b50e-f4f1fede8f6c', 'Beef Curry Udon.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'ec867786-3680-5c67-8fd3-79497de2d568', 'Southern Buttermilk Chicken Burger Meal', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'ee64a952-edd0-5ee7-9ed3-2d64c6cb6b8a', 'Mala Beef Burger Meal', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'ef6e5e30-aeef-540d-9e95-ffaa29eb9d9b', 'Ebimayo Katsu Burger', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'f00e9f11-3aa8-5358-8974-486c08a85acf', '"Royals" Beef Burger', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'f0f173f4-a6eb-588c-8a2a-9694506d1724', 'Pesto Verde + Soup Set', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'f31a626f-4b7f-56c9-8cfc-edd9e4de789f', 'Mentai Beef Udon.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'f85fa95f-bb5e-549a-b83f-7f6b6e551a65', 'Mentai Katsu Don.', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'JAPANESE'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'fd8e5196-aabc-5214-8656-d663dc5c96b8', 'Chicken 65', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'SINGAPOREAN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'fe4505b7-d9f5-5b6d-b2ae-ed4f1a7bf700', 'The Ordinary™ Classic Beef Burger Meal', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)
SELECT 'ff28db6d-caa7-541c-8833-4498c660fac1', 'Chipopo + Soup Set', 'Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete.', id, 'DINNER', NULL, 'ACTIVE', false, '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0 FROM public.cuisine WHERE code = 'WESTERN'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.place_meal (id, place_id, meal_id, display_name, price, currency, spice_level, available, availability_note, recommendation_category_code, created_at, updated_at, version)
VALUES
    ('2feccc43-d63d-5d8e-9731-656b2cade0e1', 'fb61151e-a29a-507b-91b5-09907116fc35', 'bb110370-d9f2-5b6c-9d19-c330761b0745', 'Caesar Salad Grilled Chicken Thigh', 10.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'SALAD', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('dde5fa50-e72e-57b7-a3ba-a1708c9e4e4d', 'fb61151e-a29a-507b-91b5-09907116fc35', 'c214d041-869e-57ff-915d-4ea236b70e38', 'Pan-Fried Salmon', 16.00, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'SEAFOOD', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('ac49491e-2418-5d7e-a8c2-55598705dc5c', 'fb61151e-a29a-507b-91b5-09907116fc35', '4cc5b331-2615-50df-b40f-bc4290072258', 'Braised Lamb Shank', 24.00, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('a0d86ff4-8283-5a50-ab17-bbb0f0f9083f', 'fb61151e-a29a-507b-91b5-09907116fc35', '5ef67236-67b2-5306-bac3-136b8df4a91f', 'Fish & Chips', 16.00, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'SEAFOOD', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('31a9b4d4-3276-5872-ad76-08387678e802', 'fb61151e-a29a-507b-91b5-09907116fc35', '67581f0e-6616-565b-ab6c-7d37fa50aaba', 'Grilled Chicken Chop', 13.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('64af7689-017f-5599-8994-a493ee42f36c', 'fb61151e-a29a-507b-91b5-09907116fc35', 'a328b1cf-cfae-5e79-bffe-4c53572a7153', 'Pan Seared Barramundi', 16.80, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'SEAFOOD', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('d13c3fad-950e-588e-8c6e-26e8492833e2', 'fb61151e-a29a-507b-91b5-09907116fc35', 'dbb22548-42a5-57b0-b8a4-851e3d6b8a2d', 'Beef Shepherd''s Pie', 8.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('e8e5a78b-a57e-570b-b2c6-f61a3045bf93', 'fb61151e-a29a-507b-91b5-09907116fc35', '61518333-bb41-555a-8813-ae3ab23248c9', 'Chicken Shepherd''s Pie', 8.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('394eeb44-129a-56fd-baf6-093940658cb0', 'fb61151e-a29a-507b-91b5-09907116fc35', '670700d9-058d-5442-bf28-2509830d62cd', 'Prawn & Mushroom Linguine', 14.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('5ed05500-bbf5-5176-a033-6831fd8913f2', 'fb61151e-a29a-507b-91b5-09907116fc35', '60504b15-43b0-5a05-b720-3097efce27e1', 'Salmon Spinach Linguine', 14.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('cb20f63c-e64b-55b7-8875-16e6c13ad7c5', 'fb61151e-a29a-507b-91b5-09907116fc35', '895b781f-2c10-5686-be10-7a70ba77b58d', 'Linguine with Meatballs in Tomato Sauce', 12.90, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('67ad6c1a-1a0f-5554-9374-2f9f90a8dc61', 'fb61151e-a29a-507b-91b5-09907116fc35', '8a202134-1667-59ce-9b3d-6d6d6b0c99de', 'Basic Chicken Linguine', 12.90, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('77bc6273-0510-5d2a-8157-d95c2c836fad', 'fb61151e-a29a-507b-91b5-09907116fc35', 'b2ec7ea8-127b-5436-8e9a-501e3daecf5d', 'Sauteed Wild Mushroom Linguine', 12.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('f55d3e58-2556-5c53-8211-8658aee12011', 'fb61151e-a29a-507b-91b5-09907116fc35', '2d312ebd-8a94-5b38-adfc-bba80d95ee7e', 'Linguine with Chicken in Cream Sauce', 13.00, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('1a617914-a314-552d-8269-26e3c2522af0', 'fb61151e-a29a-507b-91b5-09907116fc35', 'a117b7b1-9ae8-5b05-8632-6a40e2fbcecc', 'Beef Brisket Linguine', 13.00, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('e180c6fa-23aa-57f7-af0b-b422b9a5f650', 'fb61151e-a29a-507b-91b5-09907116fc35', 'b2dd50b0-0c43-588c-9f9e-f764607a50d1', 'Sauteed Vegetables & Mushroom Linguine', 12.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('7607ebf0-a3be-5209-80f8-6694e28ad077', 'fb61151e-a29a-507b-91b5-09907116fc35', '50325e55-299c-546f-a2fd-60d1edd6b054', 'Chicken Sausage & Spinach Penne in Tomato Cream Sauce', 12.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('42290341-3fe4-5de9-bfd4-8509fcd193bf', 'fb61151e-a29a-507b-91b5-09907116fc35', 'a02c9054-9543-55d1-a973-b35ccd95f63a', 'Mushroom & Spinach Penne in Tomato Cream', 12.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('943f9fa0-98d0-5e61-9ed6-7350ec14c346', 'fb61151e-a29a-507b-91b5-09907116fc35', 'f00e9f11-3aa8-5358-8974-486c08a85acf', '"Royals" Beef Burger', 13.80, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('9ae6b4fb-b590-5681-a06e-66c73a69ea9a', 'fb61151e-a29a-507b-91b5-09907116fc35', '41697031-4de4-580f-9093-6a0611c6de77', 'Grilled Chicken & Cheese Burger', 13.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('487be776-11b8-5529-85ff-98b8cf1a56d4', 'fb61151e-a29a-507b-91b5-09907116fc35', 'b285c3af-2558-52a1-998e-3d3f8978535a', 'Salmon Burger with Garlic Aioli', 14.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('6715c249-c64e-5730-8f06-94e402f92b4c', 'fb61151e-a29a-507b-91b5-09907116fc35', '1faf4c76-8234-516b-9b73-56ffda4cce04', 'Sauteed Mushroom Burger with Miso Cream Sauce - Beef', 14.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('c5d671d1-4ef3-5625-af61-94c312fcac6a', 'fb61151e-a29a-507b-91b5-09907116fc35', '2f9d9589-91b7-5274-aafb-9e08352050a7', 'Sauteed Mushroom Burger with Miso Cream Sauce - Chicken', 14.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('713ac4b6-95f3-5ccf-a0f5-6efeb07b5a60', 'fb61151e-a29a-507b-91b5-09907116fc35', '18ac8d83-0a62-562f-8346-a0efd8932bf7', 'Portobello Mushroom Burger', 13.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('487b1f67-3a02-52b7-ba6d-0914cc611173', 'fb61151e-a29a-507b-91b5-09907116fc35', '28f63f1b-39b7-5169-b86f-6f96774f1e30', 'Beef Brisket & Cheese Sandwich', 12.90, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'SANDWICH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('e0fec636-0f45-5e9d-bb8c-fbec5f56611d', 'fb61151e-a29a-507b-91b5-09907116fc35', '7859347a-8be6-56b2-9587-843b0713653a', 'Smoked Salmon Sandwich', 12.90, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'SANDWICH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('05931d22-205f-56f3-9fef-1d902a82c2a2', 'fb61151e-a29a-507b-91b5-09907116fc35', 'ac3a9dc7-cf08-556f-b499-37db0a67edf8', 'Grilled Vege & Cheese Sandwich', 12.00, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'SANDWICH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('4882c076-983e-5f56-a0bd-88b8f1f36e52', 'fb61151e-a29a-507b-91b5-09907116fc35', '0e539386-bc6a-52d6-9617-8f59312e8b45', 'Lamb Shank Quesadilla', 12.90, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'SANDWICH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('d0784a09-8db7-5ee1-9987-d7ff747b9d61', 'fb61151e-a29a-507b-91b5-09907116fc35', '8a154e72-0da1-5f2e-b70c-5f7a76a31969', 'Nasi Lemak Sambal Prawns & Fish', 13.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'SEAFOOD', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('1c76d568-2d54-5cf0-9466-e87d02085747', 'fb61151e-a29a-507b-91b5-09907116fc35', '86a822ef-d6b1-5efd-9bd9-7f97e5e8d544', 'Beef Rendang Nasi Lemak', 17.00, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('1dc085da-e3f7-59c7-9d48-b4121eb6d3c8', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '487ac2e6-e14a-541e-8f18-ea0b4dd0e4f8', 'Spicy Tartar Chicken Nanban Don.', 11.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('529f7fd1-3308-580d-b528-e88426b0d42e', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '0bce68cd-446e-59e8-b3e2-d68bb03becd3', 'Salted Egg Chicken Don.', 12.00, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('45766984-07e2-55b5-8aa7-206a5100eb60', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '0fe496a3-3f52-5020-826b-9253a1da0fc1', 'Chicken Katsu Don.', 11.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('8012473d-fbc4-54c7-8b9a-01aabbcd6677', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'a9e9916c-0544-59df-8870-4cc8e690b0aa', 'Spicy Garlic Miso Chicken Don.', 10.80, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('54d2e3d7-d109-5f7f-98ff-1cc3e0b8923d', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '23f49241-abac-554c-820c-bc7d0fb31950', 'Chicken Oyako Don.', 10.10, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('8b77550b-9778-5996-bc44-078e09996a70', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '0a5cc1b3-1e2d-5bf5-81fa-a5eae2d059fc', 'Teriyaki Chicken Don.', 10.80, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('b7e889c8-8271-5eea-ac0c-9318bdc6fb67', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'f85fa95f-bb5e-549a-b83f-7f6b6e551a65', 'Mentai Katsu Don.', 12.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('8fc9e151-c710-532a-923e-9c75129453e9', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'deb8016b-4218-5eef-af1f-e12e80c7b7c0', 'Tsukune & Chicken Karaage Don.', 11.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('9682025c-a2e9-5fb0-a382-5ccdc6b5ef0b', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '96dd576f-2bed-5c87-b557-2e3324121b6a', 'Sukiyaki Beef Don.', 13.70, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('7444d302-cad9-57ee-9f73-d68ef1abd63c', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'a289307f-09cb-5410-a5c5-91f1d786716d', 'Mentaiyaki Beef & Ebiko Don.', 14.40, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('36eafc79-b76a-553c-9870-70893e54fb44', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'e11a74c8-26d7-5810-bd21-eab724f64b7c', 'Black Pepper Beef Don.', 13.70, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('35a5e229-349a-56df-91ea-8ec001c5085f', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'a54eb9e2-9d8f-581f-ab17-2ca55861befa', 'Roasted Beef Don.', 16.10, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('8ce40180-0b3f-5caa-a127-20812d3a2f02', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '24f851c7-1db1-5e1d-8cb0-5a882e7dfb83', 'Mala Beef Don.', 16.10, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('9410ef00-a0e3-532d-9f08-a9a3f0a62669', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '173ad3a6-6615-53f0-8539-5112e76a6676', 'Spicy Wafu Cheese Beef Don.', 16.10, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('b3267830-7eb0-507c-9560-971846bed0c1', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'a7b7a964-0431-5088-94bf-97468e11933d', 'Beef Curry Don.', 13.70, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('01b932ff-9603-58bd-9a96-2d897ce13453', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '6127f909-a450-52a4-8aeb-f79d724dc737', 'Chicken Katsu Curry Don.', 13.70, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('0f2c92b1-0c72-560f-bbb4-c9cfac69cae3', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '380070b0-2d83-56c0-b890-d82ec95ca7b4', 'Chicken Karaage Curry Don.', 12.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('e62c3869-49a1-5503-abc8-edfbb87ed46a', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'c96bb0b5-4abb-57e1-b2e6-84cd63a18b1e', 'Minced Katsu Curry Rice.', 13.70, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'RICE_BOWL', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('8263f546-5395-5b0b-b014-0d7a8456a26e', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '6a495fd3-0a08-53dd-8a48-233a67040aed', 'Beef Udon.', 11.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'NOODLES', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('4b894729-a56d-5a61-9bf5-c2c956288456', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'eaa8a66d-b7ec-5df3-b50e-f4f1fede8f6c', 'Beef Curry Udon.', 13.70, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'NOODLES', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('0dac064f-76d8-5c21-b2c9-38cc9294d297', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'a1b9a1c5-95f3-521c-9cc0-314995f4f035', 'Spicy Garlic Beef Udon.', 12.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'NOODLES', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('14b511b2-8696-5afd-93a7-420d9c14893e', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '5efe9b48-0227-5b51-93aa-cb0536bddd0d', 'Black Pepper Beef Yaki Udon.', 12.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'NOODLES', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('0847a8a0-37d4-5962-969e-0153f4f2a901', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'f31a626f-4b7f-56c9-8cfc-edd9e4de789f', 'Mentai Beef Udon.', 16.10, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'NOODLES', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('cc2464ba-fc86-523b-b93a-c52770d50ab8', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '706301b9-c241-5a25-8996-1e241505d52f', 'Shio Kosho Tori Tonkotsu Ramen.', 11.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'NOODLES', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('5a1236ed-a1f7-5d72-9a3c-1c71f13435e8', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', 'c8c0240d-4b27-5052-9aa3-ab141d672e9b', 'Shio Kosho Aka Tonkotsu Ramen.', 12.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'NOODLES', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('50f7f461-e9d1-5b8d-a2c4-f9221e43d0c9', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '475dc7c1-b1de-5c56-ab57-c11cc09cdb71', 'Shio Kosho Kuro Tonkotsu Ramen.', 12.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'NOODLES', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('2091e887-9695-52c6-97c1-218db7c97a38', 'ff90c8dc-7fe3-50c6-aaf0-8ea10f73c782', '1c6f2bff-afdd-5064-8219-45ffb5373f54', 'Miso Soup', 2.80, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('9a374d13-2b89-57db-afc6-32fc57679c84', 'a032d001-48a7-517a-bef0-95bc39640bca', '0bb1066f-cfad-596b-a7dd-fbe560ae7d9c', 'Truffle Mushroom Cream (V)', 10.85, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('dd92f683-37dd-5c70-992b-13e3199e462e', 'a032d001-48a7-517a-bef0-95bc39640bca', '9e937aee-8d13-5601-9410-a40134f81263', 'Pesto Verde', 10.85, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('124eab60-f956-5279-97ad-719be7ee2277', 'a032d001-48a7-517a-bef0-95bc39640bca', '2145097d-ec7f-5f51-a1c3-367b29502866', 'Marinara', 10.85, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('97f7087c-4ad3-5a01-b414-b9cee1ae39c8', 'a032d001-48a7-517a-bef0-95bc39640bca', 'c0fa4fdd-271d-5ec2-93d9-3ac99c9bc949', 'Chipopo', 10.85, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('f292ed9a-57b0-5c91-bfce-ca9a199fd1df', 'a032d001-48a7-517a-bef0-95bc39640bca', 'c9331b63-bc1c-51b6-a961-71be5c3afc29', 'Krimchi', 10.85, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('f00425b7-842b-51c0-afd4-cdf454479635', 'a032d001-48a7-517a-bef0-95bc39640bca', 'ff28db6d-caa7-541c-8833-4498c660fac1', 'Chipopo + Soup Set', 11.83, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('dc3c2281-3c92-574a-8cf6-6464291105d4', 'a032d001-48a7-517a-bef0-95bc39640bca', '98d39635-da9f-5b6f-8ac5-238f4f589e6f', 'Krimchi + Soup Set', 11.83, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('017cffe2-bbe7-5a6f-a072-b79af04b1e15', 'a032d001-48a7-517a-bef0-95bc39640bca', 'f0f173f4-a6eb-588c-8a2a-9694506d1724', 'Pesto Verde + Soup Set', 11.83, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('e5e45e08-ad2d-54d2-8ff3-aefb3049706c', 'a032d001-48a7-517a-bef0-95bc39640bca', 'b70f4586-fb3c-5cb1-b5c3-38061037054a', 'Marinara + Soup Set', 11.83, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('71067d2f-cf8b-5056-b34f-219300b69944', 'a032d001-48a7-517a-bef0-95bc39640bca', '6bf7efba-bdfd-5d45-a8d2-6fe33f71358b', 'Truffle Mushroom Cream + Soup Set (V)', 11.83, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'PASTA', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('79b2c18b-1b28-5806-bee6-637c10ffafd0', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', '04765498-0254-5ff3-b9ba-83bd7fdb2364', 'O''Drumlets Combo', 9.80, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('fdf44f03-c88e-5b62-854d-82c7d750a5a8', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', 'ee64a952-edd0-5ee7-9ed3-2d64c6cb6b8a', 'Mala Beef Burger Meal', 14.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('9e79c310-eaef-5e1d-9fd6-2159b755eb22', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', '568ac2bc-d599-5976-94ca-1d4cb416cc68', 'Mala Beef Burger', 10.20, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('431fba97-eb73-531c-8450-99c307d2e6c4', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', 'fe4505b7-d9f5-5b6d-b2ae-ed4f1a7bf700', 'The Ordinary™ Classic Beef Burger Meal', 13.90, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('bea52823-2548-532b-b3e5-8d8f52617f6b', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', 'd8cc1e85-41db-5c0f-92c2-61e6a2a68716', 'The Ordinary™ Classic Beef Burger', 9.80, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('494845c5-894a-566e-a9ae-1f62b5b4bf12', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', 'cadad930-b162-506d-97d9-4b5b351c7e10', 'The Ordinary™ Classic Double Stack Meal', 19.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('01032641-e554-5535-81e1-c28ddb95be4e', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', '6af6f53d-9b2d-5e25-9412-62a63c066240', 'The Ordinary™ Classic Double Stack', 15.20, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('866303a7-c722-560e-93c2-205a30daf86f', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', '11c4ea94-f2b2-5822-a31b-5f72a1908a7e', 'Spicy Chicken Burger Meal', 12.20, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('bcc03494-d879-5713-8279-118a5c703249', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', '6abd5ecb-ce6d-5715-b203-f013a4859e25', 'Spicy Chicken Burger', 8.10, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('4313ddf5-cb52-5db2-812e-9de6fcad3865', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', 'ec867786-3680-5c67-8fd3-79497de2d568', 'Southern Buttermilk Chicken Burger Meal', 13.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('8a636a07-dc0f-5d12-b99f-83c4059e1dad', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', '33151fe8-08b4-55b7-a4f9-cbde5fb88ea2', 'Southern Buttermilk Chicken Burger', 9.20, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('b4e47f44-d420-5875-9fd7-921c706ef24a', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', '7bc9a630-8a04-5e23-be39-89925ed1acfd', 'Classic Fish Fillet Burger Meal', 12.90, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('51b46a81-cf2d-55ab-a9cb-64eac58fe7f2', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', '6bc7a179-0bd0-5785-9411-05e5bf14f089', 'Classic Fish Fillet Burger', 8.80, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('b77a59c0-43a0-50f8-b7f0-946798797328', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', 'd55958c2-0520-5c89-953a-9cd44d8f7e29', 'Ebimayo Katsu Burger Meal', 15.50, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('c2e29788-9fee-5d07-b422-2bf02d864e5e', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', 'ef6e5e30-aeef-540d-9e95-ffaa29eb9d9b', 'Ebimayo Katsu Burger', 10.90, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('330eeb59-c82a-510b-a4a6-d84689bef3a7', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', '79e50103-e956-50f3-8d14-538de6346e87', 'Classic Impossible™ Cheeseburger Meal', 23.40, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('a9ddbcef-77d1-57dd-acea-2d9a32e42b1f', '5801e48d-a6bb-5ab5-b3e7-93791ea05ada', '2d436f77-c7b1-5001-add8-a65cdef4cd84', 'Classic Impossible™ Cheeseburger', 19.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'BURGER', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('5bb3d06f-2e2d-5140-ab86-f4d6cdccb141', '5ad2685a-0bad-528f-a067-54c3916fd7ac', '99d2a88b-6a6e-5e65-a10b-90f2dd4eb9c5', 'Chicken Tikka', 9.75, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('6d3dfe44-b266-54c6-ab26-fe34ffd0e02f', '5ad2685a-0bad-528f-a067-54c3916fd7ac', '1c76872c-a5d3-57a7-8991-c996a394fb1a', 'Chicken Tikka Briyani', 11.70, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('e5576814-6e45-5d5a-96b8-cc938cd4c744', '5ad2685a-0bad-528f-a067-54c3916fd7ac', '2a2e7742-46e4-57ae-83ff-b907afc9c08c', 'Dragon Chicken', 8.45, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('506fb862-8855-5cb3-8721-ee05a1b040ce', '5ad2685a-0bad-528f-a067-54c3916fd7ac', 'fd8e5196-aabc-5214-8656-d663dc5c96b8', 'Chicken 65', 8.45, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('a547d87c-fd2d-57f7-bfc4-93d22f0b0cd8', '5ad2685a-0bad-528f-a067-54c3916fd7ac', 'c7255486-dc39-51df-8693-79d6e7756a33', 'Chicken Combo', 15.47, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('a3483ba8-2d73-5b46-8113-b99591ebaf74', '5ad2685a-0bad-528f-a067-54c3916fd7ac', '8617fb7f-9194-5e14-8035-814189da1e5c', 'Garlic Combo', 16.25, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('f20304dc-7b47-53f5-981c-ba610f8a292b', '5ad2685a-0bad-528f-a067-54c3916fd7ac', '672c1cf0-1e1c-5385-b7d7-c7bca85bf830', 'Cheese Combo', 16.25, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('9a78243c-9c0d-5462-807e-9d48965de75f', '5ad2685a-0bad-528f-a067-54c3916fd7ac', 'c11dc96a-d8a2-59eb-8cee-5cd7808903c3', 'Chapati Keema Set', 13.65, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'MAIN_DISH', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('94dbe68f-aa1d-5d44-a353-4284d9fd1566', '92ec5b73-2358-548d-bbff-c8d5e4c49993', 'cb3ef44c-7cb9-56fc-8b83-b98638cfd7e2', 'Glutinous Rice Ball', 5.00, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'DESSERT', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('4515323a-0991-505e-8667-d4d8451cab42', '92ec5b73-2358-548d-bbff-c8d5e4c49993', 'bdef6c69-84c5-53e0-b82e-cf3e069c401e', 'Almond Black Glutinous Rice', 5.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'DESSERT', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('3f73167a-d47e-5ced-9e63-23fcae499caa', '92ec5b73-2358-548d-bbff-c8d5e4c49993', '3c72cc0d-a127-5d26-a922-5e435a0e8f3a', 'Black Glutinous Rice', 4.30, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'DESSERT', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0),
    ('4aae80c8-4235-5a93-b1d2-9de389b3adc8', '92ec5b73-2358-548d-bbff-c8d5e4c49993', 'e2059627-d671-5381-a252-7521c3b374c3', 'Glutinous Rice', 4.70, 'SGD', NULL, true, 'Local ML-derived menu snapshot 2026-08-03; current availability is unverified.', 'DESSERT', '2026-08-14T00:00:00Z', '2026-08-14T00:00:00Z', 0)
ON CONFLICT (id) DO NOTHING;
