#!/usr/bin/env python3
"""Build the local-only recommendation catalogue from the pinned FoodMind ML snapshot."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import subprocess
import sys
import uuid
from pathlib import Path


EXPECTED_ML_COMMIT = "6b5b417411e04f5388d0eab39e1a57dee9d92676"
NAMESPACE = uuid.UUID("7d9608c0-65a2-4a63-a828-39b42f8a91d2")
FIXED_AT = "2026-08-14T00:00:00Z"
SOURCE_FILES = (
    "scripts/build_restaurant_side.py",
    "data/external/menu_search_targets_curated.csv",
    "data/interim/restaurant_menu_collected.csv",
    "data/external/nea_menu_search_candidates.csv",
)


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sql_text(value: object) -> str:
    if value is None or str(value).strip() == "":
        return "NULL"
    return "'" + str(value).strip().replace("'", "''") + "'"


def deterministic_uuid(kind: str, value: str) -> str:
    return str(uuid.uuid5(NAMESPACE, f"{kind}:{value.casefold().strip()}"))


def category_code(category: str, name: str) -> str:
    value = f"{category} {name}".casefold()
    rules = (
        ("DESSERT", ("dessert", "cake", "pudding")),
        ("SALAD", ("salad",)),
        ("PASTA", ("pasta", "linguine", "spaghetti")),
        ("BURGER", ("burger",)),
        ("SANDWICH", ("sandwich",)),
        ("NOODLES", ("udon", "ramen", "noodle", "chasoba")),
        ("RICE_BOWL", ("donburi", "rice bowl", " rice", "biryani")),
        ("SEAFOOD", ("seafood", "fish", "salmon", "barramundi", "prawn")),
    )
    return next((code for code, terms in rules if any(term in value for term in terms)), "MAIN_DISH")


def run_ml_build(ml_root: Path) -> None:
    subprocess.run(
        [sys.executable, str(ml_root / "scripts/build_restaurant_side.py")],
        cwd=ml_root,
        check=True,
    )


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as stream:
        return list(csv.DictReader(stream))


def selected_rows(ml_root: Path) -> tuple[list[dict[str, str]], dict[str, dict[str, str]]]:
    rows = read_csv(ml_root / "data/processed/restaurant_menu.csv")
    selected = [
        row
        for row in rows
        if row["category_group"] == "main_dish"
        and row["needs_manual_review"] == "false"
        and row["availability"] == "true"
        and row["price_sgd"].strip()
        and row["branch_match_status"] in {"target_branch_match", "manual_user_provided_menu"}
    ]
    restaurants = {
        row["restaurant_id"]: row
        for row in read_csv(ml_root / "data/processed/restaurants.csv")
        if row["restaurant_id"] in {item["restaurant_id"] for item in selected}
    }
    if len(selected) != 96 or len(restaurants) != 6:
        raise RuntimeError(
            f"Pinned ML selection drifted: expected 96 offerings across 6 restaurants, got {len(selected)} across {len(restaurants)}"
        )
    return selected, restaurants


def build_sql(rows: list[dict[str, str]], restaurants: dict[str, dict[str, str]]) -> str:
    cuisine_codes = sorted({restaurants[row["restaurant_id"]]["cuisine"].split("|")[0].upper() for row in rows})
    meals: dict[str, tuple[str, str, str]] = {}
    output = [
        "-- Generated by scripts/build-ml-local-recommendation-seed.py; do not edit by hand.",
        f"-- Source ML commit: {EXPECTED_ML_COMMIT}",
        "-- Local/Docker demonstration data only. Availability and safety metadata are not verified.",
        "",
        "INSERT INTO public.cuisine (id, code, name, created_at, updated_at, version)",
        "VALUES",
    ]
    output.append(",\n".join(
        f"    ({sql_text(deterministic_uuid('cuisine', code))}, {sql_text(code)}, {sql_text(code.title())}, {sql_text(FIXED_AT)}, {sql_text(FIXED_AT)}, 0)"
        for code in cuisine_codes
    ))
    output.append("ON CONFLICT (code) DO NOTHING;\n")

    output.extend([
        "INSERT INTO public.place (id, name, place_type, area, address_text, latitude, longitude, price_band, curation_status, created_at, updated_at, version)",
        "VALUES",
    ])
    place_values = []
    for restaurant_id, row in sorted(restaurants.items()):
        place_values.append(
            "    (" + ", ".join((
                sql_text(deterministic_uuid("place", restaurant_id)),
                sql_text(row["restaurant_name"]),
                "'RESTAURANT'",
                sql_text(row["area"]),
                sql_text(row["address"]),
                row["latitude"] or "NULL",
                row["longitude"] or "NULL",
                "NULL",
                "'ACTIVE'",
                sql_text(FIXED_AT),
                sql_text(FIXED_AT),
                "0",
            )) + ")"
        )
    output.append(",\n".join(place_values))
    output.append("ON CONFLICT (id) DO NOTHING;\n")

    for row in rows:
        restaurant = restaurants[row["restaurant_id"]]
        cuisine = restaurant["cuisine"].split("|")[0].upper()
        meal_key = f"{cuisine}|DINNER|{row['menu_item_name']}"
        meals.setdefault(
            deterministic_uuid("meal", meal_key),
            (row["menu_item_name"].strip(), cuisine, meal_key),
        )
    for meal_id, (name, cuisine, _key) in sorted(meals.items()):
        output.extend([
            "INSERT INTO public.meal (id, name, description, cuisine_id, meal_type, default_spice_level, curation_status, allergen_evidence_complete, created_at, updated_at, version)",
            "SELECT " + ", ".join((
                sql_text(meal_id),
                sql_text(name),
                sql_text("Local ML-derived menu item; ingredient, allergen, dietary and spice metadata are incomplete."),
                "id",
                "'DINNER'",
                "NULL",
                "'ACTIVE'",
                "false",
                sql_text(FIXED_AT),
                sql_text(FIXED_AT),
                "0",
            )) + f" FROM public.cuisine WHERE code = {sql_text(cuisine)}",
            "ON CONFLICT (id) DO NOTHING;\n",
        ])

    output.extend([
        "INSERT INTO public.place_meal (id, place_id, meal_id, display_name, price, currency, spice_level, available, availability_note, recommendation_category_code, created_at, updated_at, version)",
        "VALUES",
    ])
    offering_values = []
    for row in sorted(rows, key=lambda item: (item["restaurant_id"], item["restaurant_menu_id"])):
        restaurant = restaurants[row["restaurant_id"]]
        cuisine = restaurant["cuisine"].split("|")[0].upper()
        meal_key = f"{cuisine}|DINNER|{row['menu_item_name']}"
        source_key = f"{row['restaurant_id']}|{row['restaurant_menu_id']}|{row['menu_item_name']}"
        note = f"Local ML-derived menu snapshot {row['collected_at']}; current availability is unverified."
        offering_values.append(
            "    (" + ", ".join((
                sql_text(deterministic_uuid("offering", source_key)),
                sql_text(deterministic_uuid("place", row["restaurant_id"])),
                sql_text(deterministic_uuid("meal", meal_key)),
                sql_text(row["menu_item_name"]),
                row["price_sgd"],
                "'SGD'",
                "NULL",
                "true",
                sql_text(note),
                sql_text(category_code(row["category"], row["menu_item_name"])),
                sql_text(FIXED_AT),
                sql_text(FIXED_AT),
                "0",
            )) + ")"
        )
    output.append(",\n".join(offering_values))
    output.append("ON CONFLICT (id) DO NOTHING;\n")
    return "\n".join(output)


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise RuntimeError(f"Generated artifact is stale: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ml-root", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    ml_root = options.ml_root.resolve()
    actual_commit = subprocess.check_output(
        ["git", "-c", "safe.directory=*", "rev-parse", "HEAD"], cwd=ml_root, text=True
    ).strip()
    if actual_commit != EXPECTED_ML_COMMIT:
        raise RuntimeError(f"Expected ML commit {EXPECTED_ML_COMMIT}, got {actual_commit}")
    run_ml_build(ml_root)
    rows, restaurants = selected_rows(ml_root)
    sql = build_sql(rows, restaurants)
    sql_path = Path(__file__).resolve().parents[1] / "src/main/resources/db/local/R__ml_recommendation_catalogue.sql"
    manifest_path = sql_path.with_name("ml-recommendation-seed-manifest.json")
    manifest = {
        "schemaVersion": "foodmind-local-recommendation-seed-v1",
        "sourceCommit": actual_commit,
        "sourceFiles": {name: digest(ml_root / name) for name in SOURCE_FILES},
        "selection": {
            "categoryGroup": "main_dish",
            "availability": True,
            "needsManualReview": False,
            "branchMatchStatus": ["manual_user_provided_menu", "target_branch_match"],
            "requiresPrice": True,
        },
        "restaurantCount": len(restaurants),
        "offeringCount": len(rows),
        "mealCount": len({deterministic_uuid('meal', f"{restaurants[row['restaurant_id']]['cuisine'].split('|')[0].upper()}|DINNER|{row['menu_item_name']}") for row in rows}),
        "generatedSqlSha256": hashlib.sha256(sql.encode("utf-8")).hexdigest(),
    }
    manifest_text = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    write_or_check(sql_path, sql, options.check)
    write_or_check(manifest_path, manifest_text, options.check)
    print(f"local recommendation seed: {len(restaurants)} restaurants, {len(rows)} offerings -> {sql_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
