-- FoodMind database foundation.
--
-- UUID values are generated by the application, so no UUID-generation
-- extension is installed here. pg_trgm is required by the authorised search
-- indexes introduced by later migrations.

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

-- Keep mutable rows' updated_at values authoritative even when a future write
-- path does not go through Hibernate. Optimistic-lock versions remain owned by
-- the application.
CREATE FUNCTION public.foodmind_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    NEW.updated_at := statement_timestamp();
    RETURN NEW;
END;
$function$;

COMMENT ON FUNCTION public.foodmind_set_updated_at() IS
    'Sets NEW.updated_at to the current statement timestamp for mutable FoodMind rows.';
