-- Identity is retained and deactivated/anonymised rather than hard-deleted.
-- UUID primary keys are opaque values generated by the application.

CREATE TABLE app_user (
    id                 uuid         NOT NULL,
    email              varchar(320) NOT NULL,
    normalised_email   varchar(320) NOT NULL,
    password_hash      varchar(255) NOT NULL,
    display_name       varchar(100) NOT NULL,
    role               varchar(20)  NOT NULL DEFAULT 'USER',
    status             varchar(20)  NOT NULL DEFAULT 'ACTIVE',
    time_zone          varchar(64)  NOT NULL DEFAULT 'Asia/Singapore',
    created_at         timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at      timestamptz,
    deactivated_at     timestamptz,
    version            bigint       NOT NULL DEFAULT 0,

    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT ck_app_user_email_trimmed
        CHECK (email = btrim(email) AND email <> ''),
    CONSTRAINT ck_app_user_normalised_email
        CHECK (
            normalised_email = lower(btrim(email))
            AND normalised_email <> ''
        ),
    CONSTRAINT ck_app_user_password_hash_not_blank
        CHECK (password_hash = btrim(password_hash) AND password_hash <> ''),
    CONSTRAINT ck_app_user_display_name_not_blank
        CHECK (display_name = btrim(display_name) AND display_name <> ''),
    CONSTRAINT ck_app_user_role
        CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_app_user_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DEACTIVATED')),
    CONSTRAINT ck_app_user_time_zone_not_blank
        CHECK (time_zone = btrim(time_zone) AND time_zone <> ''),
    CONSTRAINT ck_app_user_deactivation_state
        CHECK (
            (status = 'DEACTIVATED' AND deactivated_at IS NOT NULL)
            OR
            (status <> 'DEACTIVATED' AND deactivated_at IS NULL)
        ),
    CONSTRAINT ck_app_user_timestamp_order
        CHECK (
            updated_at >= created_at
            AND (last_login_at IS NULL OR last_login_at >= created_at)
            AND (deactivated_at IS NULL OR deactivated_at >= created_at)
        ),
    CONSTRAINT ck_app_user_version_nonnegative
        CHECK (version >= 0)
);

COMMENT ON TABLE app_user IS
    'FoodMind user identity and account lifecycle; rows are deactivated/anonymised, not broadly deleted.';
COMMENT ON COLUMN app_user.id IS
    'Opaque application-generated UUID used as the authenticated subject.';
COMMENT ON COLUMN app_user.email IS
    'User-supplied email representation; never use this column for equality lookup.';
COMMENT ON COLUMN app_user.normalised_email IS
    'Lower-cased, trimmed email used for uniqueness and authentication lookup.';
COMMENT ON COLUMN app_user.password_hash IS
    'Adaptive one-way password hash; plaintext or encrypted passwords are prohibited.';
COMMENT ON COLUMN app_user.role IS
    'Account role: USER or the reserved ADMIN value.';
COMMENT ON COLUMN app_user.status IS
    'Account access state: ACTIVE, SUSPENDED, or DEACTIVATED.';
COMMENT ON COLUMN app_user.time_zone IS
    'IANA time-zone identifier used for user-local daily and weekly aggregation.';
COMMENT ON COLUMN app_user.version IS
    'Application-managed optimistic-lock version.';

CREATE UNIQUE INDEX uq_app_user_normalised_email
    ON app_user (normalised_email);

CREATE INDEX ix_app_user_status
    ON app_user (status);

CREATE TRIGGER trg_app_user_set_updated_at
BEFORE UPDATE ON app_user
FOR EACH ROW
EXECUTE FUNCTION public.foodmind_set_updated_at();

CREATE TABLE auth_session (
    id                       uuid        NOT NULL,
    user_id                  uuid        NOT NULL,
    token_family_id          uuid        NOT NULL,
    refresh_token_hash       char(64)    NOT NULL,
    issued_at                timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at               timestamptz NOT NULL,
    rotated_at               timestamptz,
    revoked_at               timestamptz,
    replaced_by_session_id   uuid,
    client_type              varchar(20) NOT NULL,
    device_label             varchar(100),

    CONSTRAINT pk_auth_session PRIMARY KEY (id),
    CONSTRAINT fk_auth_session_user
        FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_auth_session_identity_family
        UNIQUE (id, user_id, token_family_id),
    CONSTRAINT fk_auth_session_replacement_family
        FOREIGN KEY (
            replaced_by_session_id,
            user_id,
            token_family_id
        )
        REFERENCES auth_session (id, user_id, token_family_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_auth_session_refresh_token_hash
        UNIQUE (refresh_token_hash),
    CONSTRAINT uq_auth_session_replaced_by
        UNIQUE (replaced_by_session_id),
    CONSTRAINT ck_auth_session_refresh_token_hash
        CHECK (refresh_token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_auth_session_client_type
        CHECK (client_type IN ('WEB', 'ANDROID')),
    CONSTRAINT ck_auth_session_device_label
        CHECK (
            device_label IS NULL
            OR (device_label = btrim(device_label) AND device_label <> '')
        ),
    CONSTRAINT ck_auth_session_expiry
        CHECK (expires_at > issued_at),
    CONSTRAINT ck_auth_session_rotated_at
        CHECK (
            rotated_at IS NULL
            OR (rotated_at >= issued_at AND rotated_at <= expires_at)
        ),
    CONSTRAINT ck_auth_session_revoked_at
        CHECK (revoked_at IS NULL OR revoked_at >= issued_at),
    CONSTRAINT ck_auth_session_rotation_link
        CHECK (
            (rotated_at IS NULL AND replaced_by_session_id IS NULL)
            OR
            (rotated_at IS NOT NULL AND replaced_by_session_id IS NOT NULL)
        ),
    CONSTRAINT ck_auth_session_not_self_replaced
        CHECK (replaced_by_session_id IS NULL OR replaced_by_session_id <> id)
);

COMMENT ON TABLE auth_session IS
    'Rotating opaque refresh-token sessions; only SHA-256 token hashes are persisted.';
COMMENT ON COLUMN auth_session.token_family_id IS
    'Stable identifier for a refresh-token rotation family and reuse-detection revocation.';
COMMENT ON COLUMN auth_session.refresh_token_hash IS
    'Lower-case hexadecimal SHA-256 digest of the opaque refresh token.';
COMMENT ON COLUMN auth_session.rotated_at IS
    'Timestamp at which this token was consumed and replaced.';
COMMENT ON COLUMN auth_session.revoked_at IS
    'Timestamp at which this session became unusable, including family-wide revocation.';
COMMENT ON COLUMN auth_session.replaced_by_session_id IS
    'Next session in the one-way refresh rotation chain.';
COMMENT ON COLUMN auth_session.device_label IS
    'Optional user-facing label; it must not contain a full device fingerprint.';

CREATE INDEX ix_auth_session_user_revoked_expiry
    ON auth_session (user_id, revoked_at, expires_at);

CREATE INDEX ix_auth_session_token_family
    ON auth_session (token_family_id);

CREATE INDEX ix_auth_session_active_expiry
    ON auth_session (expires_at)
    WHERE revoked_at IS NULL;

CREATE FUNCTION public.foodmind_guard_auth_session_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
DECLARE
    successor public.auth_session%ROWTYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.revoked_at IS NULL
           AND OLD.expires_at > CURRENT_TIMESTAMP THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                MESSAGE = 'active auth sessions cannot be deleted';
        END IF;

        RETURN OLD;
    END IF;

    IF ROW(
        NEW.id,
        NEW.user_id,
        NEW.token_family_id,
        NEW.refresh_token_hash,
        NEW.issued_at,
        NEW.expires_at,
        NEW.client_type,
        NEW.device_label
    ) IS DISTINCT FROM ROW(
        OLD.id,
        OLD.user_id,
        OLD.token_family_id,
        OLD.refresh_token_hash,
        OLD.issued_at,
        OLD.expires_at,
        OLD.client_type,
        OLD.device_label
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'auth session identity and token metadata are immutable';
    END IF;

    IF OLD.rotated_at IS NOT NULL
       AND ROW(NEW.rotated_at, NEW.replaced_by_session_id)
           IS DISTINCT FROM
           ROW(OLD.rotated_at, OLD.replaced_by_session_id) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'auth session rotation cannot be cleared or repointed';
    END IF;

    IF OLD.revoked_at IS NOT NULL
       AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'auth session revocation cannot be cleared or rewritten';
    END IF;

    IF OLD.revoked_at IS NOT NULL
       AND ROW(NEW.rotated_at, NEW.replaced_by_session_id)
           IS DISTINCT FROM
           ROW(OLD.rotated_at, OLD.replaced_by_session_id) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'revoked auth sessions cannot be rotated';
    END IF;

    IF OLD.rotated_at IS NULL
       AND NEW.rotated_at IS NOT NULL THEN
        SELECT candidate.*
          INTO successor
          FROM public.auth_session AS candidate
         WHERE candidate.id = NEW.replaced_by_session_id
         FOR UPDATE;

        IF successor.id IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = '23503',
                MESSAGE = 'auth session replacement does not exist';
        END IF;

        IF successor.user_id IS DISTINCT FROM OLD.user_id
           OR successor.token_family_id IS DISTINCT FROM OLD.token_family_id
           OR successor.rotated_at IS NOT NULL
           OR successor.revoked_at IS NOT NULL
           OR successor.issued_at < NEW.rotated_at THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                MESSAGE = 'auth session replacement is not a valid forward successor';
        END IF;
    END IF;

    RETURN NEW;
END;
$function$;

CREATE TRIGGER trg_auth_session_guard_mutation
    BEFORE UPDATE OR DELETE ON auth_session
    FOR EACH ROW
    EXECUTE FUNCTION public.foodmind_guard_auth_session_mutation();
