-- Trusted groups, memberships, invitations, media metadata, and user records.
--
-- UUID values are generated by the application. User and catalogue rows are
-- deliberately retained; all foreign keys therefore use restrictive delete
-- behaviour unless the relationship is an optional catalogue snapshot.

CREATE TABLE public.trusted_group (
    id uuid PRIMARY KEY,
    name varchar(120) NOT NULL,
    description text,
    created_by_user_id uuid NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0,

    CONSTRAINT fk_trusted_group_created_by_user
        FOREIGN KEY (created_by_user_id)
        REFERENCES public.app_user (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_trusted_group_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT ck_trusted_group_description_length
        CHECK (description IS NULL OR char_length(description) <= 2000),
    CONSTRAINT ck_trusted_group_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_trusted_group_timestamps
        CHECK (updated_at >= created_at),
    CONSTRAINT ck_trusted_group_version
        CHECK (version >= 0)
);

CREATE INDEX ix_trusted_group_creator_status
    ON public.trusted_group (created_by_user_id, status, created_at DESC);

CREATE INDEX ix_trusted_group_active
    ON public.trusted_group (created_at DESC)
    WHERE status = 'ACTIVE';

CREATE TRIGGER trg_trusted_group_set_updated_at
    BEFORE UPDATE ON public.trusted_group
    FOR EACH ROW
    EXECUTE FUNCTION public.foodmind_set_updated_at();


CREATE TABLE public.group_membership (
    id uuid PRIMARY KEY,
    group_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role varchar(20) NOT NULL,
    status varchar(20) NOT NULL,
    joined_at timestamptz,
    ended_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0,

    CONSTRAINT fk_group_membership_group
        FOREIGN KEY (group_id)
        REFERENCES public.trusted_group (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_group_membership_user
        FOREIGN KEY (user_id)
        REFERENCES public.app_user (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_group_membership_group_user
        UNIQUE (group_id, user_id),
    CONSTRAINT ck_group_membership_role
        CHECK (role IN ('OWNER', 'MEMBER')),
    CONSTRAINT ck_group_membership_status
        CHECK (status IN ('INVITED', 'ACTIVE', 'LEFT', 'REMOVED')),
    CONSTRAINT ck_group_membership_lifecycle
        CHECK (
            (status = 'INVITED' AND joined_at IS NULL AND ended_at IS NULL)
            OR
            (status = 'ACTIVE' AND joined_at IS NOT NULL AND ended_at IS NULL)
            OR
            (status IN ('LEFT', 'REMOVED') AND ended_at IS NOT NULL)
        ),
    CONSTRAINT ck_group_membership_ended_after_joined
        CHECK (ended_at IS NULL OR joined_at IS NULL OR ended_at >= joined_at),
    CONSTRAINT ck_group_membership_timestamps
        CHECK (updated_at >= created_at),
    CONSTRAINT ck_group_membership_version
        CHECK (version >= 0)
);

-- A group may have at most one current owner. The create/transfer transaction
-- is responsible for ensuring that every active group has exactly one.
CREATE UNIQUE INDEX uq_group_membership_active_owner
    ON public.group_membership (group_id)
    WHERE role = 'OWNER' AND status = 'ACTIVE';

CREATE INDEX ix_group_membership_user_status
    ON public.group_membership (user_id, status, group_id);

CREATE INDEX ix_group_membership_group_status
    ON public.group_membership (group_id, status, joined_at DESC);

CREATE TRIGGER trg_group_membership_set_updated_at
    BEFORE UPDATE ON public.group_membership
    FOR EACH ROW
    EXECUTE FUNCTION public.foodmind_set_updated_at();


CREATE TABLE public.group_invitation (
    id uuid PRIMARY KEY,
    group_id uuid NOT NULL,
    token_hash char(64) NOT NULL,
    created_by_user_id uuid NOT NULL,
    expires_at timestamptz NOT NULL,
    max_uses integer NOT NULL DEFAULT 1,
    use_count integer NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_group_invitation_group
        FOREIGN KEY (group_id)
        REFERENCES public.trusted_group (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_group_invitation_created_by_user
        FOREIGN KEY (created_by_user_id)
        REFERENCES public.app_user (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_group_invitation_token_hash
        UNIQUE (token_hash),
    CONSTRAINT ck_group_invitation_token_hash
        CHECK (token_hash::text ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_group_invitation_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT ck_group_invitation_usage
        CHECK (max_uses > 0 AND use_count >= 0 AND use_count <= max_uses),
    CONSTRAINT ck_group_invitation_status
        CHECK (status IN ('ACTIVE', 'EXHAUSTED', 'REVOKED', 'EXPIRED')),
    CONSTRAINT ck_group_invitation_status_usage
        CHECK (
            (status = 'ACTIVE' AND use_count < max_uses)
            OR (status = 'EXHAUSTED' AND use_count = max_uses)
            OR status IN ('REVOKED', 'EXPIRED')
        )
);

CREATE INDEX ix_group_invitation_group_status_expiry
    ON public.group_invitation (group_id, status, expires_at);

CREATE INDEX ix_group_invitation_active_expiry
    ON public.group_invitation (expires_at)
    WHERE status = 'ACTIVE';


CREATE TABLE public.media_asset (
    id uuid PRIMARY KEY,
    owner_user_id uuid NOT NULL,
    object_key varchar(1024) NOT NULL,
    content_type varchar(100) NOT NULL,
    byte_size bigint NOT NULL,
    checksum_sha256 char(64),
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalised_at timestamptz,
    deleted_at timestamptz,

    CONSTRAINT fk_media_asset_owner
        FOREIGN KEY (owner_user_id)
        REFERENCES public.app_user (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_media_asset_object_key
        UNIQUE (object_key),
    CONSTRAINT uq_media_asset_id_owner
        UNIQUE (id, owner_user_id),
    CONSTRAINT ck_media_asset_object_key_not_blank
        CHECK (btrim(object_key) <> ''),
    CONSTRAINT ck_media_asset_content_type
        CHECK (btrim(content_type) <> '' AND content_type LIKE 'image/%'),
    CONSTRAINT ck_media_asset_byte_size
        CHECK (byte_size > 0),
    CONSTRAINT ck_media_asset_checksum
        CHECK (
            checksum_sha256 IS NULL
            OR checksum_sha256::text ~ '^[0-9a-f]{64}$'
        ),
    CONSTRAINT ck_media_asset_status
        CHECK (status IN ('PENDING', 'READY', 'DELETED')),
    CONSTRAINT ck_media_asset_lifecycle
        CHECK (
            (
                status = 'PENDING'
                AND finalised_at IS NULL
                AND deleted_at IS NULL
            )
            OR
            (
                status = 'READY'
                AND finalised_at IS NOT NULL
                AND checksum_sha256 IS NOT NULL
                AND deleted_at IS NULL
            )
            OR
            (
                status = 'DELETED'
                AND deleted_at IS NOT NULL
            )
        ),
    CONSTRAINT ck_media_asset_finalised_timestamp
        CHECK (finalised_at IS NULL OR finalised_at >= created_at),
    CONSTRAINT ck_media_asset_deleted_timestamp
        CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

CREATE INDEX ix_media_asset_owner_created
    ON public.media_asset (owner_user_id, created_at DESC);

CREATE INDEX ix_media_asset_pending_created
    ON public.media_asset (created_at)
    WHERE status = 'PENDING';

CREATE FUNCTION public.foodmind_guard_media_asset_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'media assets must be soft-deleted';
    END IF;

    IF ROW(
        NEW.id,
        NEW.owner_user_id,
        NEW.object_key,
        NEW.content_type,
        NEW.byte_size,
        NEW.created_at
    ) IS DISTINCT FROM ROW(
        OLD.id,
        OLD.owner_user_id,
        OLD.object_key,
        OLD.content_type,
        OLD.byte_size,
        OLD.created_at
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'media asset identity and declared object metadata are immutable';
    END IF;

    IF NEW IS NOT DISTINCT FROM OLD THEN
        RETURN NEW;
    END IF;

    IF OLD.status = 'DELETED' THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'deleted media assets are immutable';
    END IF;

    IF NOT (
        (OLD.status = 'PENDING' AND NEW.status IN ('READY', 'DELETED'))
        OR (OLD.status = 'READY' AND NEW.status = 'DELETED')
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'invalid media asset status transition';
    END IF;

    IF OLD.status = 'PENDING' AND NEW.status = 'READY' THEN
        IF OLD.checksum_sha256 IS NOT NULL
           AND NEW.checksum_sha256 IS DISTINCT FROM OLD.checksum_sha256 THEN
            RAISE EXCEPTION USING
                ERRCODE = '55000',
                MESSAGE = 'declared media checksum cannot change during finalisation';
        END IF;
    ELSIF ROW(NEW.checksum_sha256, NEW.finalised_at)
          IS DISTINCT FROM
          ROW(OLD.checksum_sha256, OLD.finalised_at) THEN
        RAISE EXCEPTION USING
            ERRCODE = '55000',
            MESSAGE = 'verified media metadata must be preserved during deletion';
    END IF;

    RETURN NEW;
END;
$function$;

CREATE TRIGGER trg_media_asset_guard_mutation
    BEFORE UPDATE OR DELETE ON public.media_asset
    FOR EACH ROW
    EXECUTE FUNCTION public.foodmind_guard_media_asset_mutation();


CREATE TABLE public.food_record (
    id uuid PRIMARY KEY,
    owner_user_id uuid NOT NULL,
    meal_id uuid,
    meal_name_snapshot varchar(160) NOT NULL,
    place_id uuid,
    place_name_snapshot varchar(160),
    cuisine_id uuid,
    occurred_at timestamptz NOT NULL,
    price numeric(10,2),
    currency char(3),
    rating numeric(2,1),
    comment text,
    would_eat_again boolean,
    visibility varchar(20) NOT NULL DEFAULT 'PRIVATE',
    group_id uuid,
    media_asset_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamptz,
    version bigint NOT NULL DEFAULT 0,

    CONSTRAINT fk_food_record_owner
        FOREIGN KEY (owner_user_id)
        REFERENCES public.app_user (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_food_record_meal
        FOREIGN KEY (meal_id)
        REFERENCES public.meal (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_food_record_place
        FOREIGN KEY (place_id)
        REFERENCES public.place (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_food_record_cuisine
        FOREIGN KEY (cuisine_id)
        REFERENCES public.cuisine (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_food_record_group_membership
        FOREIGN KEY (group_id, owner_user_id)
        REFERENCES public.group_membership (group_id, user_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_food_record_media_owner
        FOREIGN KEY (media_asset_id, owner_user_id)
        REFERENCES public.media_asset (id, owner_user_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_food_record_id_owner
        UNIQUE (id, owner_user_id),
    CONSTRAINT ck_food_record_meal_name
        CHECK (btrim(meal_name_snapshot) <> ''),
    CONSTRAINT ck_food_record_place_name
        CHECK (
            place_name_snapshot IS NULL
            OR btrim(place_name_snapshot) <> ''
        ),
    CONSTRAINT ck_food_record_money
        CHECK (
            (price IS NULL AND currency IS NULL)
            OR
            (
                price IS NOT NULL
                AND price >= 0
                AND price < 'Infinity'::numeric
                AND currency IS NOT NULL
                AND currency::text ~ '^[A-Z]{3}$'
            )
        ),
    CONSTRAINT ck_food_record_rating
        CHECK (rating IS NULL OR rating BETWEEN 1.0 AND 5.0),
    CONSTRAINT ck_food_record_comment_length
        CHECK (comment IS NULL OR char_length(comment) <= 4000),
    CONSTRAINT ck_food_record_visibility
        CHECK (
            (visibility = 'PRIVATE' AND group_id IS NULL)
            OR
            (visibility = 'GROUP' AND group_id IS NOT NULL)
        ),
    CONSTRAINT ck_food_record_timestamps
        CHECK (
            updated_at >= created_at
            AND (deleted_at IS NULL OR deleted_at >= created_at)
        ),
    CONSTRAINT ck_food_record_version
        CHECK (version >= 0)
);

CREATE INDEX ix_food_record_owner_occurred_active
    ON public.food_record (owner_user_id, occurred_at DESC, id)
    WHERE deleted_at IS NULL;

CREATE INDEX ix_food_record_group_occurred_active
    ON public.food_record (group_id, occurred_at DESC, id)
    WHERE visibility = 'GROUP' AND deleted_at IS NULL;

CREATE INDEX ix_food_record_meal_active
    ON public.food_record (meal_id)
    WHERE meal_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX ix_food_record_place_active
    ON public.food_record (place_id)
    WHERE place_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX ix_food_record_cuisine_active
    ON public.food_record (cuisine_id)
    WHERE cuisine_id IS NOT NULL AND deleted_at IS NULL;

CREATE TRIGGER trg_food_record_set_updated_at
    BEFORE UPDATE ON public.food_record
    FOR EACH ROW
    EXECUTE FUNCTION public.foodmind_set_updated_at();


CREATE TABLE public.drink_record (
    id uuid PRIMARY KEY,
    owner_user_id uuid NOT NULL,
    drink_name varchar(160) NOT NULL,
    place_id uuid,
    shop_name_snapshot varchar(160) NOT NULL,
    occurred_at timestamptz NOT NULL,
    price numeric(10,2),
    currency char(3),
    rating numeric(2,1),
    comment text,
    sweetness_level smallint,
    ice_level smallint,
    would_buy_again boolean,
    visibility varchar(20) NOT NULL DEFAULT 'PRIVATE',
    group_id uuid,
    media_asset_id uuid,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamptz,
    version bigint NOT NULL DEFAULT 0,

    CONSTRAINT fk_drink_record_owner
        FOREIGN KEY (owner_user_id)
        REFERENCES public.app_user (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_drink_record_place
        FOREIGN KEY (place_id)
        REFERENCES public.place (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_drink_record_group_membership
        FOREIGN KEY (group_id, owner_user_id)
        REFERENCES public.group_membership (group_id, user_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_drink_record_media_owner
        FOREIGN KEY (media_asset_id, owner_user_id)
        REFERENCES public.media_asset (id, owner_user_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_drink_record_id_owner
        UNIQUE (id, owner_user_id),
    CONSTRAINT ck_drink_record_name
        CHECK (btrim(drink_name) <> ''),
    CONSTRAINT ck_drink_record_shop_name
        CHECK (btrim(shop_name_snapshot) <> ''),
    CONSTRAINT ck_drink_record_money
        CHECK (
            (price IS NULL AND currency IS NULL)
            OR
            (
                price IS NOT NULL
                AND price >= 0
                AND price < 'Infinity'::numeric
                AND currency IS NOT NULL
                AND currency::text ~ '^[A-Z]{3}$'
            )
        ),
    CONSTRAINT ck_drink_record_rating
        CHECK (rating IS NULL OR rating BETWEEN 1.0 AND 5.0),
    CONSTRAINT ck_drink_record_comment_length
        CHECK (comment IS NULL OR char_length(comment) <= 4000),
    CONSTRAINT ck_drink_record_sweetness
        CHECK (sweetness_level IS NULL OR sweetness_level BETWEEN 0 AND 5),
    CONSTRAINT ck_drink_record_ice
        CHECK (ice_level IS NULL OR ice_level BETWEEN 0 AND 5),
    CONSTRAINT ck_drink_record_visibility
        CHECK (
            (visibility = 'PRIVATE' AND group_id IS NULL)
            OR
            (visibility = 'GROUP' AND group_id IS NOT NULL)
        ),
    CONSTRAINT ck_drink_record_timestamps
        CHECK (
            updated_at >= created_at
            AND (deleted_at IS NULL OR deleted_at >= created_at)
        ),
    CONSTRAINT ck_drink_record_version
        CHECK (version >= 0)
);

CREATE INDEX ix_drink_record_owner_occurred_active
    ON public.drink_record (owner_user_id, occurred_at DESC, id)
    WHERE deleted_at IS NULL;

CREATE INDEX ix_drink_record_group_occurred_active
    ON public.drink_record (group_id, occurred_at DESC, id)
    WHERE visibility = 'GROUP' AND deleted_at IS NULL;

CREATE INDEX ix_drink_record_place_active
    ON public.drink_record (place_id)
    WHERE place_id IS NOT NULL AND deleted_at IS NULL;

CREATE TRIGGER trg_drink_record_set_updated_at
    BEFORE UPDATE ON public.drink_record
    FOR EACH ROW
    EXECUTE FUNCTION public.foodmind_set_updated_at();

COMMENT ON COLUMN public.food_record.meal_name_snapshot IS
    'Immutable display snapshot retained even when the linked catalogue item changes.';
COMMENT ON COLUMN public.food_record.place_name_snapshot IS
    'Point-in-time place label; may also represent a user-entered, unlinked place.';
COMMENT ON COLUMN public.drink_record.shop_name_snapshot IS
    'Point-in-time shop label retained independently of the optional place link.';
COMMENT ON COLUMN public.media_asset.object_key IS
    'Server-issued object-storage key; clients must never be allowed to supply arbitrary keys.';
